### ISSUE TITLE
Handler is not recompiled on dependent file change

### ISSUE THREAD

**Issue by m-butler** [architect/plugin-typescript#6]
**Describe the issue**
The plugin works well for handlers. However, i'm having an issue when changing code in the shared folder, because the handler is not recompiled after the change. I have to manually trigger save in the handler file again to recompile the dependent code.

**Steps to reproduce**
1. Create a handler (i.e. get-index/index.ts)
2. Create a file in shared (i.e. shared/manager/UserManager.ts)
3. Import that file and use it in your handler
4. Make a change in the UserManager.ts file
5. Observe that the handler is not recompiled
6. Go back to the handler and manually save the file again. Notice that the code is now compiled correctly including the dependent code.

**Expected behavior**
The affected handlers are recompiled on dependent code changes.

**Comment by ryanblock** [comment]
Please check out v0.3.0-RC.0 and let me know if this fixes things? Thanks!

**Comment by ryanblock** [comment]
Bump @m-butler!

**Comment by m-butler** [comment]
@ryanblock  Seems to be working as expected now! 😃

**Comment by ryanblock** [comment]
Released to prod in 0.3.0!
